from __future__ import annotations

import contextlib
import importlib.util
import io
import sys
import tempfile
import unittest
from pathlib import Path
from types import ModuleType
from unittest.mock import patch

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "tooling/sync/generate_agent_rules.py"


def _load_script_module() -> ModuleType:
    spec = importlib.util.spec_from_file_location("generate_agent_rules_module", SCRIPT_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class GenerateAgentRulesTests(unittest.TestCase):
    script: ModuleType

    @classmethod
    def setUpClass(cls) -> None:
        cls.script = _load_script_module()

    def test_generates_agents_and_claude_append_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            project_base = tmp_path / "project-base.md"
            cycle_rules = tmp_path / "development-cycle.md"
            agents_append_path = tmp_path / "Scaffold_AGENTS.append.md"
            claude_append_path = tmp_path / "Scaffold_CLAUDE.append.md"

            project_base.write_text("# AGENTS.md\n\n## Base\n- base rule\n", encoding="utf-8")
            cycle_rules.write_text("## Cycle\n- cycle rule\n", encoding="utf-8")

            argv = [
                "generate_agent_rules.py",
                "--project-base",
                str(project_base),
                "--cycle-rules",
                str(cycle_rules),
                "--agents-append-path",
                str(agents_append_path),
                "--claude-append-path",
                str(claude_append_path),
            ]

            with patch.object(sys, "argv", argv):
                stdout = io.StringIO()
                stderr = io.StringIO()
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    exit_code = self.script.main()

            self.assertEqual(exit_code, 0)

            agents_append = agents_append_path.read_text(encoding="utf-8")
            claude_append = claude_append_path.read_text(encoding="utf-8")

            self.assertIn("Generated by tooling/sync/generate_agent_rules.py", agents_append)
            self.assertIn("# AGENTS.md", agents_append)
            self.assertIn("## Cycle", agents_append)

            self.assertIn("Generated by tooling/sync/generate_agent_rules.py", claude_append)
            self.assertIn("# CLAUDE.md", claude_append)
            self.assertIn("## Cycle", claude_append)

    def test_rewrites_heading_when_h1_is_not_first_line(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            project_base = tmp_path / "project-base.md"
            cycle_rules = tmp_path / "development-cycle.md"
            agents_append_path = tmp_path / "Scaffold_AGENTS.append.md"
            claude_append_path = tmp_path / "Scaffold_CLAUDE.append.md"

            project_base.write_text(
                "<!-- preface -->\n\n# Original heading\n\n## Base\n- base rule\n",
                encoding="utf-8",
            )
            cycle_rules.write_text("## Cycle\n- cycle rule\n", encoding="utf-8")

            argv = [
                "generate_agent_rules.py",
                "--project-base",
                str(project_base),
                "--cycle-rules",
                str(cycle_rules),
                "--agents-append-path",
                str(agents_append_path),
                "--claude-append-path",
                str(claude_append_path),
            ]

            with patch.object(sys, "argv", argv):
                stdout = io.StringIO()
                stderr = io.StringIO()
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    exit_code = self.script.main()

            self.assertEqual(exit_code, 0)
            self.assertIn("# AGENTS.md", agents_append_path.read_text(encoding="utf-8"))
            self.assertIn("# CLAUDE.md", claude_append_path.read_text(encoding="utf-8"))

    def test_fails_if_non_generated_append_file_exists(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            project_base = tmp_path / "project-base.md"
            cycle_rules = tmp_path / "development-cycle.md"
            agents_append_path = tmp_path / "Scaffold_AGENTS.append.md"
            claude_append_path = tmp_path / "Scaffold_CLAUDE.append.md"

            project_base.write_text("# AGENTS.md\n\n## Base\n- base rule\n", encoding="utf-8")
            cycle_rules.write_text("## Cycle\n- cycle rule\n", encoding="utf-8")
            agents_append_path.write_text("# manual append\n", encoding="utf-8")

            argv = [
                "generate_agent_rules.py",
                "--project-base",
                str(project_base),
                "--cycle-rules",
                str(cycle_rules),
                "--agents-append-path",
                str(agents_append_path),
                "--claude-append-path",
                str(claude_append_path),
            ]

            with patch.object(sys, "argv", argv):
                stdout = io.StringIO()
                stderr = io.StringIO()
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    exit_code = self.script.main()

            self.assertEqual(exit_code, 2)
            self.assertIn(
                "refusing to overwrite without --force-overwrite-existing", stderr.getvalue()
            )

    def test_force_overwrite_existing_allows_replacement(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            project_base = tmp_path / "project-base.md"
            cycle_rules = tmp_path / "development-cycle.md"
            agents_append_path = tmp_path / "Scaffold_AGENTS.append.md"
            claude_append_path = tmp_path / "Scaffold_CLAUDE.append.md"

            project_base.write_text("# AGENTS.md\n\n## Base\n- base rule\n", encoding="utf-8")
            cycle_rules.write_text("## Cycle\n- cycle rule\n", encoding="utf-8")
            agents_append_path.write_text("# manual append\n", encoding="utf-8")
            claude_append_path.write_text("# manual append\n", encoding="utf-8")

            argv = [
                "generate_agent_rules.py",
                "--project-base",
                str(project_base),
                "--cycle-rules",
                str(cycle_rules),
                "--agents-append-path",
                str(agents_append_path),
                "--claude-append-path",
                str(claude_append_path),
                "--force-overwrite-existing",
            ]

            with patch.object(sys, "argv", argv):
                stdout = io.StringIO()
                stderr = io.StringIO()
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    exit_code = self.script.main()

            self.assertEqual(exit_code, 0)
            self.assertIn("# AGENTS.md", agents_append_path.read_text(encoding="utf-8"))
            self.assertIn("# CLAUDE.md", claude_append_path.read_text(encoding="utf-8"))

    def test_repository_generated_append_files_are_in_sync(self) -> None:
        project_base = (
            (REPO_ROOT / "docs/agent-rules/project-base.md").read_text(encoding="utf-8").strip()
        )
        cycle_rules = (
            (REPO_ROOT / "docs/agent-rules/development-cycle.md")
            .read_text(encoding="utf-8")
            .strip()
        )

        expected_agents = self.script._render_append(project_base, cycle_rules, heading="AGENTS.md")
        expected_claude = self.script._render_append(project_base, cycle_rules, heading="CLAUDE.md")

        actual_agents = (REPO_ROOT / "Scaffold_AGENTS.append.md").read_text(encoding="utf-8")
        actual_claude = (REPO_ROOT / "Scaffold_CLAUDE.append.md").read_text(encoding="utf-8")

        self.assertEqual(actual_agents, expected_agents)
        self.assertEqual(actual_claude, expected_claude)


if __name__ == "__main__":
    unittest.main()
