#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


GENERATED_HEADER = (
    "<!-- Generated by tooling/sync/generate_agent_rules.py. "
    "Do not edit this file directly; edit docs/agent-rules/*.md and regenerate. -->"
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Scaffold agent append files from canonical rule sources"
    )
    parser.add_argument("--project-base", default="docs/agent-rules/project-base.md")
    parser.add_argument("--cycle-rules", default="docs/agent-rules/development-cycle.md")
    parser.add_argument("--agents-append-path", default="Scaffold_AGENTS.append.md")
    parser.add_argument("--claude-append-path", default="Scaffold_CLAUDE.append.md")
    parser.add_argument(
        "--force-overwrite-existing",
        action="store_true",
        help="allow replacing existing non-generated append files",
    )
    return parser.parse_args()


def _resolve_path(repo_root: Path, raw: str) -> Path:
    path = Path(raw)
    if path.is_absolute():
        return path
    return repo_root / path


def _read_required(path: Path) -> str:
    try:
        content = path.read_text(encoding="utf-8").strip()
    except OSError as exc:
        raise ValueError(f"failed to read {path}: {exc}") from exc
    if not content:
        raise ValueError(f"rule source is empty: {path}")
    return content


def _rewrite_primary_heading(markdown: str, heading: str) -> str:
    lines = markdown.splitlines()
    if not lines:
        return markdown
    if lines[0].startswith("# "):
        lines[0] = f"# {heading}"
    return "\n".join(lines)


def _render_append(project_base: str, cycle_rules: str, *, heading: str) -> str:
    target_base = _rewrite_primary_heading(project_base, heading)
    return f"{GENERATED_HEADER}\n\n{target_base}\n\n{cycle_rules}\n"


def _is_generated_file(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"failed to read {path}: {exc}") from exc
    return content.startswith(GENERATED_HEADER)


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _guard_overwrite(path: Path, *, force: bool) -> None:
    if path.exists() and not force and not _is_generated_file(path):
        raise ValueError(
            f"{path} exists and is not generated by this tool; "
            "refusing to overwrite without --force-overwrite-existing"
        )


def main() -> int:
    args = _parse_args()
    repo_root = Path(__file__).resolve().parents[2]

    project_base_path = _resolve_path(repo_root, args.project_base)
    cycle_rules_path = _resolve_path(repo_root, args.cycle_rules)
    agents_append_path = _resolve_path(repo_root, args.agents_append_path)
    claude_append_path = _resolve_path(repo_root, args.claude_append_path)

    try:
        project_base = _read_required(project_base_path)
        cycle_rules = _read_required(cycle_rules_path)
        rendered_agents_append = _render_append(project_base, cycle_rules, heading="AGENTS.md")
        rendered_claude_append = _render_append(project_base, cycle_rules, heading="CLAUDE.md")

        _guard_overwrite(agents_append_path, force=args.force_overwrite_existing)
        _guard_overwrite(claude_append_path, force=args.force_overwrite_existing)

        _ensure_parent(agents_append_path)
        _ensure_parent(claude_append_path)
        agents_append_path.write_text(rendered_agents_append, encoding="utf-8")
        claude_append_path.write_text(rendered_claude_append, encoding="utf-8")

        print(agents_append_path)
        print(claude_append_path)
        return 0
    except (ValueError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
