#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tooling.sync.lib.command_surface_loader import (  # noqa: E402
    CommandSurfaceLoadError,
    load_command_catalog,
)

GENERATED_HEADER = (
    "<!-- Generated by tooling/sync/generate_markdown_command_exports.py. "
    "Do not edit this file directly; edit framework/scripts/manifest.yaml and regenerate. -->"
)
_AGENTS = ("claude", "opencode")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate OpenCode command markdown and Claude skill markdown from manifest"
    )
    parser.add_argument(
        "--manifest",
        default="framework/scripts/manifest.yaml",
        help="Path to manifest YAML (default: framework/scripts/manifest.yaml)",
    )
    parser.add_argument(
        "--agent",
        choices=(*_AGENTS, "all"),
        default="all",
        help="Target export surface (default: all)",
    )
    parser.add_argument(
        "--repo-root",
        default=str(REPO_ROOT),
        help="Repository root for writing generated outputs",
    )
    parser.add_argument(
        "--output-root",
        default=None,
        help="Optional override root for generated files",
    )
    parser.add_argument(
        "--enable-conditional",
        action="store_true",
        help="Generate conditional preview outputs instead of default root exports",
    )
    parser.add_argument(
        "--force-overwrite-existing",
        action="store_true",
        help="allow replacing existing non-generated files",
    )
    parser.add_argument(
        "--write-active-surfaces",
        action="store_true",
        help="write the selected surface into the live root agent directories",
    )
    parser.add_argument(
        "--sync-preview-snapshot",
        action="store_true",
        help="update the conditional preview snapshot in the same invocation as active surfaces",
    )
    return parser.parse_args()


def _target_agents(agent: str) -> tuple[str, ...]:
    if agent == "all":
        return _AGENTS
    return (agent,)


def _resolve_repo_root(raw: str) -> Path:
    root = Path(raw)
    if root.is_absolute():
        return root
    return Path.cwd() / root


def _is_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise CommandSurfaceLoadError(f"failed to read {path}: {exc}") from exc
    lines = content.splitlines()
    index = 0
    if lines and lines[0] == "---":
        index = 1
        while index < len(lines) and lines[index] != "---":
            index += 1
        if index == len(lines):
            return False
        index += 1
    while index < len(lines) and not lines[index].strip():
        index += 1
    return index < len(lines) and lines[index] == GENERATED_HEADER


def _guard_overwrite(path: Path, *, force: bool) -> None:
    if path.exists() and not force and not _is_generated_file(path):
        raise CommandSurfaceLoadError(
            f"{path} exists and is not generated by this tool; "
            "refusing to overwrite without --force-overwrite-existing"
        )


def _root_output_base(
    *,
    agent: str,
    repo_root: Path,
    include_conditional: bool,
    write_active_surfaces: bool,
) -> Path:
    if include_conditional and not write_active_surfaces:
        return repo_root / "tooling/sync/generated/with-conditional/markdown" / agent
    return repo_root


def _guard_conditional_surface_downgrade(
    *,
    agent: str,
    all_commands: list[dict[str, Any]],
    output_base: Path,
    repo_root: Path,
    include_conditional: bool,
    force: bool,
) -> None:
    if include_conditional or force or output_base != repo_root:
        return

    conditional_commands = [command for command in all_commands if command["tier"] == "conditional"]
    for command in conditional_commands:
        path = _target_path(agent=agent, base_root=output_base, slug=command["slug"])
        if path.exists() and _is_generated_file(path):
            raise CommandSurfaceLoadError(
                "live conditional markdown surfaces already exist; rerun with "
                "--enable-conditional --write-active-surfaces to preserve them"
            )


def _target_path(*, agent: str, base_root: Path, slug: str) -> Path:
    if agent == "opencode":
        return base_root / ".opencode/commands" / f"{slug}.md"
    return base_root / ".claude/skills" / slug / "SKILL.md"


def _render_opencode(command: dict[str, Any], manifest_path: str) -> str:
    lines = [
        "---",
        f"description: {command['summary']}",
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"# {command['id']}",
        "",
        "## Purpose",
        command["summary"],
        "",
        "## When To Use",
        command["when_to_use"],
        "",
        "## Required Contracts",
    ]
    for contract in command["required_contracts"]:
        lines.append(
            f"- `{contract['id']}` - {contract['description']} (`{contract['validator']}`)"
        )
    lines.extend(
        [
            "",
            "## Next Commands",
        ]
    )
    for next_step in command["next_steps"]:
        lines.append(f"- `{next_step}`")
    lines.extend(
        [
            "",
            "## Source Of Truth",
            f"- `{manifest_path}`",
            "- `framework/docs/contract/workflow-map.md`",
            "",
        ]
    )
    return "\n".join(lines)


def _render_claude(command: dict[str, Any], manifest_path: str) -> str:
    lines = [
        "---",
        f"name: {command['slug']}",
        (
            f"description: Handles Scaffold `{command['id']}` contract guidance "
            "and required evidence."
        ),
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"# {command['id']}",
        "",
        "## Purpose",
        command["summary"],
        "",
        "## When To Use",
        command["when_to_use"],
        "",
        "## Required Contracts",
    ]
    for contract in command["required_contracts"]:
        lines.append(f"- `{contract['id']}` - {contract['description']}")
    lines.extend(["", "## Next Commands"])
    for next_step in command["next_steps"]:
        lines.append(f"- `{next_step}`")
    lines.extend(
        [
            "",
            "## Source Of Truth",
            f"- `{manifest_path}`",
            "- `framework/docs/contract/workflow-map.md`",
            "",
        ]
    )
    return "\n".join(lines)


def _render_command(*, agent: str, command: dict[str, Any], manifest_path: str) -> str:
    if agent == "opencode":
        return _render_opencode(command, manifest_path)
    return _render_claude(command, manifest_path)


def _filter_commands_for_surface(
    commands: list[dict[str, Any]], *, include_conditional: bool
) -> list[dict[str, Any]]:
    allowed_ids = {
        command["id"] for command in commands if include_conditional or command["tier"] == "core"
    }
    filtered_commands: list[dict[str, Any]] = []
    for command in commands:
        if not include_conditional and command["tier"] != "core":
            continue
        filtered_command = dict(command)
        filtered_command["next_steps"] = [
            step for step in command["next_steps"] if step in allowed_ids
        ]
        filtered_commands.append(filtered_command)
    return filtered_commands


def _guard_output_override(repo_root: Path, output_root: Path) -> None:
    resolved_repo_root = repo_root.resolve()
    resolved_output_root = output_root.resolve()
    filesystem_root = Path(resolved_output_root.anchor)
    if resolved_output_root == resolved_repo_root:
        raise CommandSurfaceLoadError(
            "--output-root must not point at the repository root; use a dedicated directory"
        )
    if resolved_output_root == resolved_repo_root.parent:
        raise CommandSurfaceLoadError(
            "--output-root must not point at the repository parent; use a dedicated directory"
        )
    if resolved_output_root == filesystem_root:
        raise CommandSurfaceLoadError("--output-root must not point at the filesystem root")


def _resolve_output_root(repo_root: Path, output_root: Path) -> Path:
    if output_root.is_absolute():
        root_base = output_root
    else:
        root_base = repo_root / output_root
    _guard_output_override(repo_root, root_base)
    return root_base


def _remove_stale_outputs(
    stale_paths: list[Path],
    *,
    output_base: Path,
) -> None:
    for candidate in stale_paths:
        candidate.unlink()
        parent = candidate.parent
        while parent != output_base and parent.exists():
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent


def _collect_stale_outputs(
    *,
    agent: str,
    desired_paths: set[Path],
    output_base: Path,
    force: bool,
) -> list[Path]:
    if not output_base.exists():
        return []

    if agent == "opencode":
        candidates = sorted(output_base.glob(".opencode/commands/*.md"))
    else:
        candidates = sorted(output_base.glob(".claude/skills/*/SKILL.md"))

    stale_paths: list[Path] = []
    for candidate in candidates:
        if candidate in desired_paths:
            continue
        if not _is_generated_file(candidate):
            if not force:
                raise CommandSurfaceLoadError(
                    f"{candidate} is stale but not generated by this tool; refusing to delete"
                )
        stale_paths.append(candidate)
    return stale_paths


def _write_agent_outputs(
    *,
    agent: str,
    all_commands: list[dict[str, Any]],
    commands: list[dict[str, Any]],
    manifest_path: str,
    output_base: Path,
    repo_root: Path,
    include_conditional: bool,
    force: bool,
) -> tuple[list[Path], list[tuple[Path, str]], list[Path]]:
    desired_paths: set[Path] = set()
    rendered_outputs: list[tuple[Path, str]] = []

    _guard_conditional_surface_downgrade(
        agent=agent,
        all_commands=all_commands,
        output_base=output_base,
        repo_root=repo_root,
        include_conditional=include_conditional,
        force=force,
    )

    for command in commands:
        path = _target_path(agent=agent, base_root=output_base, slug=command["slug"])
        desired_paths.add(path)
        _guard_overwrite(path, force=force)

    stale_paths = _collect_stale_outputs(
        agent=agent, desired_paths=desired_paths, output_base=output_base, force=force
    )

    for command in commands:
        path = _target_path(agent=agent, base_root=output_base, slug=command["slug"])
        rendered_outputs.append(
            (path, _render_command(agent=agent, command=command, manifest_path=manifest_path))
        )

    return sorted(desired_paths), rendered_outputs, stale_paths


def _apply_agent_output_plan(
    *,
    rendered_outputs: list[tuple[Path, str]],
    stale_paths: list[Path],
    output_base: Path,
) -> list[Path]:
    written_paths: list[Path] = []
    for path, content in rendered_outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written_paths.append(path)

    _remove_stale_outputs(stale_paths, output_base=output_base)
    return written_paths


def main() -> int:
    args = _parse_args()
    repo_root = _resolve_repo_root(args.repo_root)
    output_root = Path(args.output_root) if args.output_root else None

    try:
        if output_root is not None and args.write_active_surfaces:
            raise CommandSurfaceLoadError(
                "--write-active-surfaces cannot be combined with --output-root"
            )
        if args.sync_preview_snapshot and not args.write_active_surfaces:
            raise CommandSurfaceLoadError(
                "--sync-preview-snapshot requires --write-active-surfaces"
            )
        if args.sync_preview_snapshot and not args.enable_conditional:
            raise CommandSurfaceLoadError("--sync-preview-snapshot requires --enable-conditional")
        catalog = load_command_catalog(repo_root, args.manifest)
        commands = _filter_commands_for_surface(
            catalog["commands"], include_conditional=args.enable_conditional
        )
        planned_outputs: list[tuple[Path, list[tuple[Path, str]], list[Path]]] = []

        if output_root is not None:
            root_base = _resolve_output_root(repo_root, output_root)
            for agent in _target_agents(args.agent):
                agent_root = root_base / agent
                _, rendered_outputs, stale_paths = _write_agent_outputs(
                    agent=agent,
                    all_commands=catalog["commands"],
                    commands=commands,
                    manifest_path=catalog["manifest_path"],
                    output_base=agent_root,
                    repo_root=repo_root,
                    include_conditional=args.enable_conditional,
                    force=args.force_overwrite_existing,
                )
                planned_outputs.append((agent_root, rendered_outputs, stale_paths))
            for agent_root, rendered_outputs, stale_paths in planned_outputs:
                paths = _apply_agent_output_plan(
                    rendered_outputs=rendered_outputs,
                    stale_paths=stale_paths,
                    output_base=agent_root,
                )
                for path in paths:
                    print(path)
            return 0

        for agent in _target_agents(args.agent):
            agent_root = _root_output_base(
                agent=agent,
                repo_root=repo_root,
                include_conditional=args.enable_conditional,
                write_active_surfaces=args.write_active_surfaces,
            )
            _, rendered_outputs, stale_paths = _write_agent_outputs(
                agent=agent,
                all_commands=catalog["commands"],
                commands=commands,
                manifest_path=catalog["manifest_path"],
                output_base=agent_root,
                repo_root=repo_root,
                include_conditional=args.enable_conditional,
                force=args.force_overwrite_existing,
            )
            planned_outputs.append((agent_root, rendered_outputs, stale_paths))
        if args.sync_preview_snapshot:
            preview_root = repo_root / "tooling/sync/generated/with-conditional/markdown"
            for agent in _target_agents(args.agent):
                preview_agent_root = preview_root / agent
                _, rendered_outputs, stale_paths = _write_agent_outputs(
                    agent=agent,
                    all_commands=catalog["commands"],
                    commands=commands,
                    manifest_path=catalog["manifest_path"],
                    output_base=preview_agent_root,
                    repo_root=repo_root,
                    include_conditional=True,
                    force=args.force_overwrite_existing,
                )
                planned_outputs.append((preview_agent_root, rendered_outputs, stale_paths))
        for agent_root, rendered_outputs, stale_paths in planned_outputs:
            paths = _apply_agent_output_plan(
                rendered_outputs=rendered_outputs,
                stale_paths=stale_paths,
                output_base=agent_root,
            )
            for path in paths:
                print(path)
        return 0
    except (CommandSurfaceLoadError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
