#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Literal, NamedTuple

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tooling.sync.lib.command_surface_loader import (  # noqa: E402
    CommandCatalogEntry,
    CommandSurfaceLoadError,
    load_command_catalog,
)

GENERATED_HEADER = (
    "<!-- Generated by tooling/sync/generate_markdown_command_exports.py. "
    "Do not edit this file directly; edit framework/scripts/manifest.yaml and regenerate. -->"
)
_DEFAULT_MANIFEST = "framework/scripts/manifest.yaml"

AgentName = Literal["claude", "opencode"]
_AGENTS: tuple[AgentName, AgentName] = ("claude", "opencode")
RenderedOutput = tuple[Path, str]


class ExportContext(NamedTuple):
    repo_root: Path
    manifest_path: str
    all_commands: list[CommandCatalogEntry]
    commands: list[CommandCatalogEntry]
    include_conditional: bool
    force: bool


class AgentOutputPlan(NamedTuple):
    output_base: Path
    rendered_outputs: list[RenderedOutput]
    stale_paths: list[Path]


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate OpenCode command markdown and Claude skill markdown from manifest"
    )
    parser.add_argument(
        "--manifest",
        default=_DEFAULT_MANIFEST,
        help="Path to manifest YAML (default: framework/scripts/manifest.yaml)",
    )
    parser.add_argument(
        "--agent",
        choices=(*_AGENTS, "all"),
        default="all",
        help="Target export surface (default: all)",
    )
    parser.add_argument(
        "--repo-root",
        default=str(REPO_ROOT),
        help="Repository root for writing generated outputs",
    )
    parser.add_argument(
        "--output-root",
        default=None,
        help="Optional override root for generated files",
    )
    parser.add_argument(
        "--enable-conditional",
        action="store_true",
        help="Generate conditional preview outputs instead of default root exports",
    )
    parser.add_argument(
        "--force-overwrite-existing",
        action="store_true",
        help="allow replacing existing non-generated files",
    )
    parser.add_argument(
        "--write-active-surfaces",
        action="store_true",
        help="write the selected surface into the live root agent directories",
    )
    parser.add_argument(
        "--sync-preview-snapshot",
        action="store_true",
        help="update the conditional preview snapshot in the same invocation as active surfaces",
    )
    return parser.parse_args()


def _target_agents(agent: str) -> tuple[AgentName, ...]:
    if agent == "all":
        return _AGENTS
    if agent == "claude":
        return ("claude",)
    return ("opencode",)


def _resolve_repo_root(raw: str) -> Path:
    root = Path(raw)
    if root.is_absolute():
        return root
    return Path.cwd() / root


def _resolve_manifest_path(repo_root: Path, manifest_arg: str) -> Path:
    manifest_path = Path(manifest_arg)
    if manifest_path.is_absolute():
        return manifest_path
    if manifest_arg == _DEFAULT_MANIFEST:
        return repo_root / manifest_path
    return Path.cwd() / manifest_path


def _is_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise CommandSurfaceLoadError(f"failed to read {path}: {exc}") from exc
    lines = content.splitlines()
    index = 0
    if lines and lines[0] == "---":
        index = 1
        while index < len(lines) and lines[index] != "---":
            index += 1
        if index == len(lines):
            return False
        index += 1
    while index < len(lines) and not lines[index].strip():
        index += 1
    return index < len(lines) and lines[index] == GENERATED_HEADER


def _guard_overwrite(path: Path, *, force: bool) -> None:
    if path.exists() and not force and not _is_generated_file(path):
        raise CommandSurfaceLoadError(
            f"{path} exists and is not generated by this tool; "
            "refusing to overwrite without --force-overwrite-existing"
        )


def _root_output_base(
    *,
    agent: AgentName,
    repo_root: Path,
    include_conditional: bool,
    write_active_surfaces: bool,
) -> Path:
    if include_conditional and not write_active_surfaces:
        return repo_root / "tooling/sync/generated/with-conditional/markdown" / agent
    return repo_root / "framework"


def _live_surface_root(repo_root: Path) -> Path:
    return repo_root / "framework"


def _conditional_commands(commands: list[CommandCatalogEntry]) -> list[CommandCatalogEntry]:
    return [command for command in commands if command["tier"] == "conditional"]


def _guard_conditional_surface_downgrade(
    context: ExportContext,
    agent: AgentName,
    output_base: Path,
) -> None:
    if (
        context.include_conditional
        or context.force
        or output_base != _live_surface_root(context.repo_root)
    ):
        return

    for command in _conditional_commands(context.all_commands):
        path = _target_path(agent=agent, base_root=output_base, slug=command["slug"])
        if path.exists() and _is_generated_file(path):
            raise CommandSurfaceLoadError(
                "live conditional markdown surfaces already exist; rerun with "
                "--enable-conditional --write-active-surfaces to preserve them"
            )


def _target_path(*, agent: AgentName, base_root: Path, slug: str) -> Path:
    if agent == "opencode":
        return base_root / ".opencode/commands" / f"{slug}.md"
    return base_root / ".claude/skills" / slug / "SKILL.md"


def _render_opencode(command: CommandCatalogEntry, manifest_path: str) -> str:
    description = json.dumps(command["summary"], ensure_ascii=True)
    lines = [
        "---",
        f"description: {description}",
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"# {command['id']}",
        "",
        "## Purpose",
        command["summary"],
        "",
        "## When To Use",
        command["when_to_use"],
        "",
        "## Required Contracts",
    ]
    for contract in command["required_contracts"]:
        lines.append(
            f"- `{contract['id']}` - {contract['description']} (`{contract['validator']}`)"
        )
    lines.extend(
        [
            "",
            "## Next Commands",
        ]
    )
    for next_step in command["next_steps"]:
        lines.append(f"- `{next_step}`")
    lines.extend(
        [
            "",
            "## Source Of Truth",
            f"- `{manifest_path}`",
            "- `framework/docs/contract/workflow-map.md`",
            "",
        ]
    )
    return "\n".join(lines)


def _render_claude(command: CommandCatalogEntry, manifest_path: str) -> str:
    description = json.dumps(
        f"Handles Scaffold `{command['id']}` contract guidance and required evidence.",
        ensure_ascii=True,
    )
    lines = [
        "---",
        f"name: {command['slug']}",
        f"description: {description}",
        "---",
        "",
        GENERATED_HEADER,
        "",
        f"# {command['id']}",
        "",
        "## Purpose",
        command["summary"],
        "",
        "## When To Use",
        command["when_to_use"],
        "",
        "## Required Contracts",
    ]
    for contract in command["required_contracts"]:
        lines.append(f"- `{contract['id']}` - {contract['description']}")
    lines.extend(["", "## Next Commands"])
    for next_step in command["next_steps"]:
        lines.append(f"- `{next_step}`")
    lines.extend(
        [
            "",
            "## Source Of Truth",
            f"- `{manifest_path}`",
            "- `framework/docs/contract/workflow-map.md`",
            "",
        ]
    )
    return "\n".join(lines)


def _render_command(*, agent: AgentName, command: CommandCatalogEntry, manifest_path: str) -> str:
    if agent == "opencode":
        return _render_opencode(command, manifest_path)
    return _render_claude(command, manifest_path)


def _copy_command_with_next_steps(
    command: CommandCatalogEntry,
    next_steps: list[str],
) -> CommandCatalogEntry:
    return {
        "id": command["id"],
        "slug": command["slug"],
        "tier": command["tier"],
        "summary": command["summary"],
        "when_to_use": command["when_to_use"],
        "next_steps": next_steps,
        "required_contracts": command["required_contracts"],
    }


def _filter_commands_for_surface(
    commands: list[CommandCatalogEntry],
    *,
    include_conditional: bool,
) -> list[CommandCatalogEntry]:
    allowed_ids = {
        command["id"] for command in commands if include_conditional or command["tier"] == "core"
    }
    filtered_commands: list[CommandCatalogEntry] = []
    for command in commands:
        if not include_conditional and command["tier"] != "core":
            continue
        filtered_commands.append(
            _copy_command_with_next_steps(
                command,
                [step for step in command["next_steps"] if step in allowed_ids],
            )
        )
    return filtered_commands


def _guard_output_override(repo_root: Path, output_root: Path) -> None:
    resolved_repo_root = repo_root.resolve()
    resolved_output_root = output_root.resolve()
    filesystem_root = Path(resolved_output_root.anchor)
    if resolved_output_root == resolved_repo_root:
        raise CommandSurfaceLoadError(
            "--output-root must not point at the repository root; use a dedicated directory"
        )
    if resolved_output_root == resolved_repo_root.parent:
        raise CommandSurfaceLoadError(
            "--output-root must not point at the repository parent; use a dedicated directory"
        )
    if resolved_output_root == filesystem_root:
        raise CommandSurfaceLoadError("--output-root must not point at the filesystem root")


def _resolve_output_root(repo_root: Path, output_root: Path) -> Path:
    root_base = output_root if output_root.is_absolute() else repo_root / output_root
    _guard_output_override(repo_root, root_base)
    return root_base


def _remove_stale_outputs(
    stale_paths: list[Path],
    *,
    output_base: Path,
) -> None:
    for candidate in stale_paths:
        candidate.unlink()
        parent = candidate.parent
        while parent != output_base and parent.exists():
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent


def _collect_stale_outputs(
    *,
    agent: AgentName,
    desired_paths: set[Path],
    output_base: Path,
    force: bool,
) -> list[Path]:
    if not output_base.exists():
        return []

    if agent == "opencode":
        candidates = sorted(output_base.glob(".opencode/commands/*.md"))
    else:
        candidates = sorted(output_base.glob(".claude/skills/*/SKILL.md"))

    stale_paths: list[Path] = []
    for candidate in candidates:
        if candidate in desired_paths:
            continue
        if not _is_generated_file(candidate) and not force:
            raise CommandSurfaceLoadError(
                f"{candidate} is stale but not generated by this tool; refusing to delete"
            )
        stale_paths.append(candidate)
    return stale_paths


def _desired_output_paths(
    agent: AgentName,
    output_base: Path,
    commands: list[CommandCatalogEntry],
) -> set[Path]:
    return {
        _target_path(agent=agent, base_root=output_base, slug=command["slug"])
        for command in commands
    }


def _guard_desired_overwrites(desired_paths: set[Path], *, force: bool) -> None:
    for path in desired_paths:
        _guard_overwrite(path, force=force)


def _render_outputs(
    agent: AgentName,
    commands: list[CommandCatalogEntry],
    manifest_path: str,
    output_base: Path,
) -> list[RenderedOutput]:
    return [
        (
            _target_path(agent=agent, base_root=output_base, slug=command["slug"]),
            _render_command(agent=agent, command=command, manifest_path=manifest_path),
        )
        for command in commands
    ]


def _plan_agent_outputs(
    context: ExportContext,
    agent: AgentName,
    output_base: Path,
) -> AgentOutputPlan:
    desired_paths = _desired_output_paths(agent, output_base, context.commands)
    _guard_conditional_surface_downgrade(context, agent, output_base)
    _guard_desired_overwrites(desired_paths, force=context.force)
    stale_paths = _collect_stale_outputs(
        agent=agent,
        desired_paths=desired_paths,
        output_base=output_base,
        force=context.force,
    )
    return AgentOutputPlan(
        output_base=output_base,
        rendered_outputs=_render_outputs(
            agent, context.commands, context.manifest_path, output_base
        ),
        stale_paths=stale_paths,
    )


def _apply_agent_output_plan(
    *,
    rendered_outputs: list[RenderedOutput],
    stale_paths: list[Path],
    output_base: Path,
) -> list[Path]:
    written_paths: list[Path] = []
    for path, content in rendered_outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written_paths.append(path)

    _remove_stale_outputs(stale_paths, output_base=output_base)
    return written_paths


def _validate_export_args(args: argparse.Namespace, *, output_root: Path | None) -> None:
    if output_root is not None and args.write_active_surfaces:
        raise CommandSurfaceLoadError(
            "--write-active-surfaces cannot be combined with --output-root"
        )
    if args.sync_preview_snapshot and not args.write_active_surfaces:
        raise CommandSurfaceLoadError("--sync-preview-snapshot requires --write-active-surfaces")
    if args.sync_preview_snapshot and not args.enable_conditional:
        raise CommandSurfaceLoadError("--sync-preview-snapshot requires --enable-conditional")


def _load_export_context(
    repo_root: Path,
    manifest_arg: str,
    *,
    include_conditional: bool,
    force: bool,
) -> ExportContext:
    manifest_path = _resolve_manifest_path(repo_root, manifest_arg)
    catalog = load_command_catalog(repo_root, manifest_path)
    return ExportContext(
        repo_root=repo_root,
        manifest_path=catalog["manifest_path"],
        all_commands=catalog["commands"],
        commands=_filter_commands_for_surface(
            catalog["commands"],
            include_conditional=include_conditional,
        ),
        include_conditional=include_conditional,
        force=force,
    )


def _plan_custom_output_root(
    context: ExportContext,
    agents: tuple[AgentName, ...],
    output_root: Path,
) -> list[AgentOutputPlan]:
    root_base = _resolve_output_root(context.repo_root, output_root)
    return [_plan_agent_outputs(context, agent, root_base / agent) for agent in agents]


def _plan_live_outputs(
    context: ExportContext,
    agents: tuple[AgentName, ...],
    *,
    write_active_surfaces: bool,
) -> list[AgentOutputPlan]:
    return [
        _plan_agent_outputs(
            context,
            agent,
            _root_output_base(
                agent=agent,
                repo_root=context.repo_root,
                include_conditional=context.include_conditional,
                write_active_surfaces=write_active_surfaces,
            ),
        )
        for agent in agents
    ]


def _plan_preview_outputs(
    context: ExportContext,
    agents: tuple[AgentName, ...],
) -> list[AgentOutputPlan]:
    preview_context = context._replace(include_conditional=True)
    preview_root = context.repo_root / "tooling/sync/generated/with-conditional/markdown"
    return [_plan_agent_outputs(preview_context, agent, preview_root / agent) for agent in agents]


def _apply_and_print_output_plans(plans: list[AgentOutputPlan]) -> None:
    for plan in plans:
        for path in _apply_agent_output_plan(
            rendered_outputs=plan.rendered_outputs,
            stale_paths=plan.stale_paths,
            output_base=plan.output_base,
        ):
            print(path)


def main() -> int:
    args = _parse_args()

    try:
        repo_root = _resolve_repo_root(args.repo_root)
        output_root = Path(args.output_root) if args.output_root else None
        _validate_export_args(args, output_root=output_root)
        agents = _target_agents(args.agent)
        context = _load_export_context(
            repo_root,
            args.manifest,
            include_conditional=args.enable_conditional,
            force=args.force_overwrite_existing,
        )

        if output_root is not None:
            _apply_and_print_output_plans(_plan_custom_output_root(context, agents, output_root))
            return 0

        preview_plans = _plan_preview_outputs(context, agents) if args.sync_preview_snapshot else []
        live_plans = _plan_live_outputs(
            context,
            agents,
            write_active_surfaces=args.write_active_surfaces,
        )
        _apply_and_print_output_plans([*preview_plans, *live_plans])
        return 0
    except (CommandSurfaceLoadError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
